import { getAccessToken } from './token.js';
import { generateUUID } from './utils.js';

/**
 * @typedef {Object} Amount
 * @property {number} value - Amount in minor units (e.g., 1000 for 10.00).
 * @property {'NOK' | 'DKK' | 'EUR'} currency - Currency code.
 */

/**
 * @typedef {Object} PaymentMethod
 * @property {'WALLET' | 'CARD' | 'CARD_PASSTHROUGH'} type - The type of payment method.
 */

/**
 * @typedef {Object} Customer
 * @property {string} phoneNumber - The customer's phone number.
 */

/**
 * @typedef {Object} CreatePaymentRequest
 * @property {Amount} amount - The amount to be charged.
 * @property {string} reference - Your unique identifier for the payment (8–64 characters).
 * @property {PaymentMethod} paymentMethod - The payment method type.
 * @property {'WEB_REDIRECT' | 'PUSH_MESSAGE' | 'QR' | 'NATIVE_REDIRECT'} userFlow - The flow for the user.
 * @property {string} [returnUrl] - The URL to return to after the payment.
 * @property {string} [paymentDescription] - Description shown to the user.
 * @property {Customer} [customer] - Customer information.
 * @property {string} [expiresAt] - ISO 8601 timestamp for when the payment expires.
 * @property {Object} [metadata] - A key-value map (max 5 pairs) for custom data.
 */

/**
 * @typedef {Object} PaymentResponse
 * @property {string} reference - Your unique identifier for the payment.
 * @property {string} redirectUrl - The URL where the user is redirected to.
 * @property {string} paymentId - The unique ID for the payment.
 */

/**
 * @typedef {Object} PaymentAggregate
 * @property {Amount} authorizedAmount - The total amount authorized (reserved).
 * @property {Amount} capturedAmount - The total amount successfully captured.
 * @property {Amount} refundedAmount - The total amount refunded.
 * @property {Amount} cancelledAmount - The total amount cancelled.
 */

/**
 * @typedef {Object} PaymentDetails
 * @property {string} reference - Your unique identifier for the payment.
 * @property {'CREATED' | 'AUTHORIZED' | 'CAPTURED' | 'CANCELLED' | 'REFUNDED' | 'ABORTED' | 'EXPIRED'} state - The current lifecycle stage.
 * @property {Amount} amount - The amount of the payment.
 * @property {PaymentAggregate} aggregate - Summary of all financial actions.
 * @property {PaymentMethod} paymentMethod - The payment method used.
 * @property {string} pspReference - Unique ID generated by Vipps MobilePay.
 * @property {Object} [metadata] - Custom data attached to the payment.
 */

/**
 * @typedef {Object} AdjustmentResponse
 * @property {PaymentAggregate} aggregate - The updated totals for the payment.
 */

/**
 * @typedef {Object} CapturePaymentRequest
 * @property {Amount} modificationAmount - The amount to capture.
 */

/**
 * @typedef {Object} RefundPaymentRequest
 * @property {Amount} modificationAmount - The amount to refund.
 */

/**
 * Internal helper to send a request to the ePayment API.
 * 
 * @param {import('./client.js').VippsInstance} vipps 
 * @param {string} method 
 * @param {string} path 
 * @param {Object} [body] 
 * @param {string} [idempotencyKey] 
 * @returns {Promise<any>}
 */
async function sendRequest(vipps, method, path, body, idempotencyKey) {
  const token = await getAccessToken(vipps);
  const baseUrl = vipps.config.useTestMode 
    ? 'https://apitest.vipps.no' 
    : 'https://api.vippsmobilepay.com';
  
  /** @type {Record<string, string>} */
  const headers = {
    'Authorization': `Bearer ${token}`,
    'Ocp-Apim-Subscription-Key': vipps.config.subscriptionKey,
    'Merchant-Serial-Number': vipps.config.merchantSerialNumber,
    'Content-Type': 'application/json',
  };

  if (idempotencyKey) {
    headers['Idempotency-Key'] = idempotencyKey;
  }

  if (vipps.config.systemName) {
    headers['Vipps-System-Name'] = vipps.config.systemName;
  }
  if (vipps.config.systemVersion) {
    headers['Vipps-System-Version'] = vipps.config.systemVersion;
  }
  if (vipps.config.pluginName) {
    headers['Vipps-System-Plugin-Name'] = vipps.config.pluginName;
  }
  if (vipps.config.pluginVersion) {
    headers['Vipps-System-Plugin-Version'] = vipps.config.pluginVersion;
  }

  const response = await fetch(`${baseUrl}/epayment/v1/payments${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({}));
    throw { status: response.status, ...errorBody };
  }

  return response.json();
}

/**
 * Initiates a new payment session.
 * 
 * @param {import('./client.js').VippsInstance} vipps - The Vipps instance.
 * @param {CreatePaymentRequest} body - The payment request body.
 * @returns {Promise<PaymentResponse>} The payment response from Vipps.
 */
export async function createPayment(vipps, body) {
  const key = body.reference || generateUUID();
  return sendRequest(vipps, 'POST', '', body, key);
}

/**
 * Retrieves the current status and details of a payment.
 * 
 * @param {import('./client.js').VippsInstance} vipps - The Vipps instance.
 * @param {string} reference - The unique identifier for the payment.
 * @returns {Promise<PaymentDetails>} The current state of the payment.
 */
export async function getPayment(vipps, reference) {
  return sendRequest(vipps, 'GET', `/${reference}`);
}

/**
 * Captures a previously authorized payment.
 * 
 * @param {import('./client.js').VippsInstance} vipps - The Vipps instance.
 * @param {string} reference - The unique identifier for the payment.
 * @param {CapturePaymentRequest} body - The capture request body.
 * @returns {Promise<AdjustmentResponse>} The capture response.
 */
export async function capturePayment(vipps, reference, body) {
  return sendRequest(vipps, 'POST', `/${reference}/capture`, body, reference);
}

/**
 * Cancels an authorized payment that hasn't been captured yet.
 * 
 * @param {import('./client.js').VippsInstance} vipps - The Vipps instance.
 * @param {string} reference - The unique identifier for the payment.
 * @returns {Promise<AdjustmentResponse>} The cancel response.
 */
export async function cancelPayment(vipps, reference) {
  return sendRequest(vipps, 'POST', `/${reference}/cancel`, {}, reference);
}

/**
 * Refunds a previously captured payment.
 * 
 * @param {import('./client.js').VippsInstance} vipps - The Vipps instance.
 * @param {string} reference - The unique identifier for the payment.
 * @param {RefundPaymentRequest} body - The refund request body.
 * @returns {Promise<AdjustmentResponse>} The refund response.
 */
export async function refundPayment(vipps, reference, body) {
  return sendRequest(vipps, 'POST', `/${reference}/refund`, body, reference);
}
