/**
 * @typedef {Object} VippsConfig
 * @property {string} clientId - The Client ID for the sales unit.
 * @property {string} clientSecret - The Client Secret for the sales unit.
 * @property {string} subscriptionKey - The Subscription Key for the sales unit.
 * @property {string} merchantSerialNumber - Your unique Merchant Serial Number (MSN).
 * @property {boolean} [useTestMode=false] - Whether to use the test environment.
 * @property {string} [systemName] - The name of your ecommerce solution or system.
 * @property {string} [systemVersion] - The version number of your system.
 * @property {string} [pluginName] - The name of the ecommerce plugin.
 * @property {string} [pluginVersion] - The version number of the plugin.
 * @property {Function} [getToken] - Optional external token getter.
 * @property {Function} [setToken] - Optional external token setter.
 */

/**
 * @typedef {Object} VippsInstance
 * @property {VippsConfig} config - The library configuration.
 * @property {Object} _auth - Internal state for token caching.
 * @property {string|null} _auth.token - Cached access token.
 * @property {number} _auth.expiresAt - Expiry timestamp in milliseconds.
 */

/**
 * @typedef {Object} AccessTokenResponse
 * @property {string} token_type - Always "Bearer".
 * @property {number} expires_in - Validity period in seconds.
 * @property {string} expires_on - Expiry time as a Unix timestamp (UTC).
 * @property {string} access_token - The JWT (JSON Web Token).
 */

/**
 * @typedef {Object} Amount
 * @property {number} value - Amount in minor units (e.g., 1000 for 10.00).
 * @property {string} currency - Currency code (e.g., "NOK", "DKK", "EUR").
 */

/**
 * @typedef {Object} PaymentMethod
 * @property {string} type - The type of payment method (e.g., "WALLET", "CARD").
 */

/**
 * @typedef {Object} Customer
 * @property {string} phoneNumber - The customer's phone number.
 */

/**
 * @typedef {Object} CreatePaymentRequest
 * @property {Amount} amount - The amount to be charged.
 * @property {string} reference - Your unique identifier for the payment (8–64 characters).
 * @property {PaymentMethod} paymentMethod - The payment method type.
 * @property {string} userFlow - The flow for the user (e.g., "WEB_REDIRECT", "PUSH_MESSAGE").
 * @property {string} [returnUrl] - The URL to return to after the payment.
 * @property {string} [paymentDescription] - Description shown to the user.
 * @property {Customer} [customer] - Customer information.
 * @property {string} [expiresAt] - ISO 8601 timestamp for when the payment expires.
 * @property {Object} [metadata] - A key-value map (max 5 pairs) for custom data.
 */

/**
 * @typedef {Object} PaymentResponse
 * @property {string} reference - Your unique identifier for the payment.
 * @property {string} redirectUrl - The URL where the user is redirected to.
 * @property {string} paymentId - The unique ID for the payment.
 */

/**
 * @typedef {Object} PaymentAggregate
 * @property {Amount} authorizedAmount - The total amount authorized (reserved).
 * @property {Amount} capturedAmount - The total amount successfully captured.
 * @property {Amount} refundedAmount - The total amount refunded.
 * @property {Amount} cancelledAmount - The total amount cancelled.
 */

/**
 * @typedef {Object} PaymentDetails
 * @property {string} reference - Your unique identifier for the payment.
 * @property {string} state - The current lifecycle stage (e.g., AUTHORIZED, CAPTURED).
 * @property {Amount} amount - The amount of the payment.
 * @property {PaymentAggregate} aggregate - Summary of all financial actions.
 * @property {PaymentMethod} paymentMethod - The payment method used.
 * @property {string} pspReference - Unique ID generated by Vipps MobilePay.
 * @property {Object} [metadata] - Custom data attached to the payment.
 */

/**
 * @typedef {Object} AdjustmentResponse
 * @property {PaymentAggregate} aggregate - The updated totals for the payment.
 */

/**
 * @typedef {Object} CapturePaymentRequest
 * @property {Amount} modificationAmount - The amount to capture.
 */

/**
 * @typedef {Object} RefundPaymentRequest
 * @property {Amount} modificationAmount - The amount to refund.
 */

export {};
